import Link from "next/link";
import type { AdminContext } from "../../shared/config/admin-context";
import type { BffResult } from "../../shared/bff/types";
import type { ConsentConfigurationState, ConsentIntegrationCatalogEntry, ConsentScopeType } from "./consent-configuration-admin";
import { createNextConsentDraftAction, deleteConsentHistoricalVersionAction, publishConsentDraftAction, returnConsentOverrideToInheritanceAction, validateConsentDraftAction } from "./consent-configuration-admin-actions";
import { ConsentConfigurationForm } from "./consent-configuration-form-client";

const scopes: ConsentScopeType[] = ["SHOP", "ORGANIZATION"];
const date = (value: string) => Number.isNaN(new Date(value).getTime()) ? value : new Intl.DateTimeFormat("es-ES", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const scopeLabel = (scopeType: ConsentScopeType) => scopeType === "SHOP" ? "Shop" : "Organization";
const approvedServices = (configuration: ConsentConfigurationState["published"] | null) => configuration?.policy.services.filter((service) => service.integration).length ?? 0;

export function ConsentConfigurationAdminPage({ canPublish, canWrite, context, historyResults, integrationCatalog, integrationCatalogError, notice, result, scopeType, tab }: { canPublish: boolean; canWrite: boolean; context: AdminContext; historyResults?: Array<{ scopeType: ConsentScopeType; result: BffResult<ConsentConfigurationState> }>; integrationCatalog: ConsentIntegrationCatalogEntry[]; integrationCatalogError?: string; notice?: string; result: BffResult<ConsentConfigurationState>; scopeType: ConsentScopeType; tab?: "HISTORY" }) {
  const state = result.ok ? result.data : null;
  const draft = state?.draft ?? null;
  const published = state?.published ?? null;
  const effective = state?.effective ?? null;
  const effectivePublished = effective?.published ?? null;
  const inherited = Boolean(effective?.source && (effective.source.scopeType !== state?.selectedScope.scopeType || effective.source.scopeId !== state?.selectedScope.scopeId));
  const canReturnToInheritance = Boolean(canWrite && published?.isActive && scopeType !== "ORGANIZATION");
  return <main className="adminPage">
    <div className="adminBreadcrumb">Admin / Configuracion / Consentimiento</div>
    <div className="adminPageHeader"><div><h1 className="adminPageTitle">Consentimiento de tecnologías</h1><p className="adminPageIntro">Configura servicios aprobados para la Organization o Shop activa. Publicar una revisión hace que Storefront use la nueva versión.</p></div></div>
    {notice ? <div className="adminBanner">{notice}</div> : null}
    <nav className="adminButtonRow" aria-label="Secciones de Consentimiento">{scopes.map((scope) => <Link className={!tab && scope === scopeType ? "adminButton adminButtonPrimary" : "adminButton"} href={`/admin/configuracion/consent?scopeType=${scope}`} key={scope}>{scope === "SHOP" ? "Shop" : "Organization"}</Link>)}<Link className={tab === "HISTORY" ? "adminButton adminButtonPrimary" : "adminButton"} href="/admin/configuracion/consent?tab=HISTORY">Historial</Link></nav>
    {tab === "HISTORY" ? <section className="adminCard"><h2>Historial de versiones</h2><p className="adminHelpText">Solo se puede eliminar una versión sustituida que no tenga recibos asociados. La versión publicada y toda evidencia de consentimiento permanecen protegidas.</p>{historyResults?.map(({ scopeType: historyScope, result: historyResult }) => <div key={historyScope}><h3>{scopeLabel(historyScope)}</h3>{!historyResult.ok ? <p className="adminBanner adminBannerError">{historyResult.error}</p> : historyResult.data.history.length ? <div className="adminTableScroller"><table className="adminTable"><thead><tr><th>Versión</th><th>Estado</th><th>Publicada</th><th>Servicios</th><th>Acción</th></tr></thead><tbody>{historyResult.data.history.map((version) => <tr key={version.configurationVersionId}><td>v{version.version}</td><td>{version.status}</td><td>{version.publishedAt ? date(version.publishedAt) : "—"}</td><td>{approvedServices(version)}</td><td>{version.status === "SUPERSEDED" && canWrite ? <form action={deleteConsentHistoricalVersionAction} className="adminButtonRow"><input name="configurationVersionId" type="hidden" value={version.configurationVersionId} /><input name="expectedUpdatedAt" type="hidden" value={version.updatedAt} /><input name="confirmDelete" placeholder="ELIMINAR" aria-label={`Confirmar eliminación de versión ${version.version}`} /><button className="adminButton" type="submit">Eliminar</button></form> : <span className="adminHelpText">Protegida</span>}</td></tr>)}</tbody></table></div> : <p className="adminHelpText">No hay versiones para este alcance.</p>}</div>)}</section> : <>
    {!result.ok ? <section className="adminBanner adminBannerError"><strong>No se pudo cargar Consentimiento.</strong><p>{result.error}</p><p>Contexto: <code>{context.organizationId || "Organization pendiente"}</code> / <code>{context.shopName || context.shopAlias || "Shop pendiente"}</code></p></section> : null}
    {state ? <>
      <section className="adminSummaryGrid" aria-label="Estado de Consentimiento"><div><span>Nivel editado</span><strong>{scopeLabel(scopeType)}</strong></div><div><span>Borrador propio</span><strong>{draft ? `v${draft.version}` : "No existe"}</strong></div><div><span>Publicado propio</span><strong>{published ? `v${published.version}` : "No existe"}</strong></div></section>
      <div className="consentConfigurationStatusPanels">
      <section className="adminCard consentConfigurationStatusCard" aria-label="Configuración efectiva"><h2>Configuración que se aplica</h2>{effective?.status === "AVAILABLE" && effective.source && effectivePublished ? <><p>{inherited ? <>Esta {scopeLabel(scopeType)} hereda la versión {effective.source.version} de <strong>{scopeLabel(effective.source.scopeType)}</strong>.</> : <>Esta {scopeLabel(scopeType)} usa su propia versión publicada {effective.source.version}.</>}</p><p className="adminHelpText">Incluye {effectivePublished.policy.purposes.length} categorías y {approvedServices(effectivePublished)} servicio{approvedServices(effectivePublished) === 1 ? "" : "s"} aprobado{approvedServices(effectivePublished) === 1 ? "" : "s"}.</p></> : <p>No hay una configuración publicada aplicable. Las tecnologías opcionales permanecerán bloqueadas.</p>}</section>
      {published ? <section className="adminCard consentConfigurationStatusCard"><h2>Versión publicada</h2><p>Versión {published.version}, publicada {published.publishedAt ? date(published.publishedAt) : "sin fecha"}. Tiene {published.policy.purposes.length} categorías y {approvedServices(published)} servicio{approvedServices(published) === 1 ? "" : "s"} aprobado{approvedServices(published) === 1 ? "" : "s"}.</p>{published.isActive ? <div className="adminButtonRow">{!draft && canWrite ? <form action={createNextConsentDraftAction}><input name="configurationId" type="hidden" value={published.configurationId} /><input name="scopeType" type="hidden" value={scopeType} /><button className="adminButton" type="submit">Crear siguiente revisión</button></form> : null}{canReturnToInheritance ? <form action={returnConsentOverrideToInheritanceAction}><input name="configurationId" type="hidden" value={published.configurationId} /><input name="expectedUpdatedAt" type="hidden" value={published.updatedAt} /><input name="scopeType" type="hidden" value={scopeType} /><label className="adminField"><span>Confirmación</span><input name="confirmInheritance" placeholder="Escribe HEREDAR" /></label><button className="adminButton" type="submit">Volver a heredar</button></form> : null}</div> : <div className="adminBanner adminBannerInfo">Esta versión propia está inactiva. Se aplica la configuración heredada y el historial se conserva.</div>}</section> : null}
      {draft ? <section className="adminCard consentConfigurationStatusCard"><h2>Borrador v{draft.version}</h2><p>Última edición: {date(draft.updatedAt)}. Validar no publica; publicar exige confirmación y permiso independiente.</p><div className="adminButtonRow consentDraftActions">{canWrite ? <form className="consentDraftValidateAction" action={validateConsentDraftAction}><input name="configurationVersionId" type="hidden" value={draft.configurationVersionId} /><input name="scopeType" type="hidden" value={scopeType} /><button className="adminButton" type="submit">Validar borrador</button></form> : null}{canPublish ? <form className="consentDraftPublishAction" action={publishConsentDraftAction}><input name="configurationVersionId" type="hidden" value={draft.configurationVersionId} /><input name="expectedUpdatedAt" type="hidden" value={draft.updatedAt} /><input name="scopeType" type="hidden" value={scopeType} /><label className="adminField"><span>Confirmación</span><input name="confirmPublish" placeholder="Escribe PUBLICAR" /></label><button className="adminButton adminButtonPrimary" type="submit">Publicar</button></form> : null}</div></section> : null}
      </div>
      {draft ? (canWrite ? <ConsentConfigurationForm configuration={draft} integrationCatalog={integrationCatalog} integrationCatalogError={integrationCatalogError} scopeType={scopeType} /> : <div className="adminBanner adminBannerInfo">Tienes acceso de lectura; falta <code>consent.configuration.write</code> para editar.</div>) : !published && canWrite ? <ConsentConfigurationForm configuration={null} inheritedConfiguration={inherited ? effectivePublished : null} integrationCatalog={integrationCatalog} integrationCatalogError={integrationCatalogError} scopeType={scopeType} /> : !published ? <div className="adminBanner adminBannerInfo">No existe una configuración para este scope y no tienes permiso para crearla.</div> : null}
      <section className="adminCard"><h2>Límites actuales</h2><p>La apariencia y los textos generales del banner todavía no forman parte del contrato Consent. Esta pantalla no simula esos campos: las finalidades y servicios publicados son la fuente de verdad.</p></section>
    </> : null}</>}
  </main>;
}
