"use client";

import { useMemo, useRef, useState } from "react";
import type { AdminContext } from "../../shared/config/admin-context";

type StockImportItem = { externalId?: string | null; variantId: string; warehouseId: string; onHandQuantity: number; reservedQuantity?: number; safetyStockQuantity?: number; quarantineQuantity?: number };
type Status = { jobId: string; state: string; total: number; applied: number; conflicts: number; projected: number; pending: number; pendingProjection: number; lastError: string | null };
type Phase = "idle" | "validating" | "submitting" | "polling" | "completed" | "failed";
const chunkSize = 10_000;
const terminal = new Set(["COMPLETED", "COMPLETED_WITH_CONFLICTS", "FAILED"]);
function sleep(ms: number) { return new Promise((resolve) => setTimeout(resolve, ms)); }
function normalizeHeader(value: string) { return value.trim().toLowerCase().replace(/[\s_-]+/g, ""); }
function operationId() { return crypto.randomUUID(); }
function detectDelimiter(text: string) { const header = text.split(/\r?\n/, 1)[0] ?? ""; return [";", ",", "\t"].sort((a,b)=>header.split(b).length-header.split(a).length)[0]; }
function parseCsv(text: string) {
  const delimiter = detectDelimiter(text); const rows: string[][] = []; let field=""; let row: string[]=[]; let quoted=false;
  for (let i=0;i<text.length;i+=1) { const c=text[i], n=text[i+1]; if(c==='"'){ if(quoted&&n==='"'){field+='"'; i+=1;} else quoted=!quoted; continue;} if(!quoted&&c===delimiter){row.push(field.trim()); field=""; continue;} if(!quoted&&(c==='\n'||c==='\r')){ if(c==='\r'&&n==='\n') i+=1; row.push(field.trim()); if(row.some(Boolean)) rows.push(row); row=[]; field=""; continue;} field+=c; }
  row.push(field.trim()); if(row.some(Boolean)) rows.push(row); const headers=(rows.shift()??[]).map(normalizeHeader);
  return rows.map((cells,index)=>({ rowNumber:index+2, row: headers.reduce<Record<string,string>>((acc,h,i)=>{ if(h) acc[h]=cells[i]??""; return acc; }, {}) }));
}
function value(row: Record<string,string>, names: string[]) { for (const name of names) { const v=row[name]; if(v?.trim()) return v.trim(); } return undefined; }
function numberValue(input: string | undefined, fallback=0) { if (!input) return fallback; const parsed=Number(input.replace(",", ".")); return Number.isInteger(parsed) && parsed >= 0 ? parsed : NaN; }
function rowToItem(row: Record<string,string>, rowNumber: number): { item?: StockImportItem; error?: string } {
  const variantId=value(row,["variantid","skuid","itemid"]); const warehouseId=value(row,["warehouseid","warehouse","almacen"]) ?? "main-warehouse"; const onHand=numberValue(value(row,["onhandquantity","onhand","quantity","stock","cantidad"]));
  if(!variantId) return { error: `Fila ${rowNumber}: falta variantId.` }; if(!Number.isInteger(onHand)) return { error: `Fila ${rowNumber}: onHandQuantity debe ser entero >= 0.` };
  return { item: { externalId: value(row,["externalid","id"]), variantId, warehouseId, onHandQuantity: onHand, reservedQuantity: numberValue(value(row,["reservedquantity","reserved"]),0), safetyStockQuantity: numberValue(value(row,["safetystockquantity","safetystock"]),0), quarantineQuantity: numberValue(value(row,["quarantinequantity","quarantine"]),0) } };
}
function isCsvFile(file: File) { return file.name.toLowerCase().endsWith(".csv") && (!file.type || ["text/csv", "application/csv", "application/vnd.ms-excel", "text/plain"].includes(file.type)); }
function processed(status: Status) { return Math.min(status.total, Math.max(status.applied + status.conflicts, status.projected)); }
export function StockBulkImportClient({ context }: { context: AdminContext }) {
  const [phase,setPhase]=useState<Phase>("idle"); const [message,setMessage]=useState("Selecciona un CSV de stock para comenzar."); const [error,setError]=useState<string|null>(null); const [fileName,setFileName]=useState<string|null>(null); const [total,setTotal]=useState(0); const [valid,setValid]=useState(0); const [jobs,setJobs]=useState<Status[]>([]); const [rowErrors,setRowErrors]=useState<string[]>([]); const abort=useRef(false);
  const progress=useMemo(()=>{ const done=jobs.reduce((s,j)=>s+processed(j),0); return { done, percent: Math.round((done/Math.max(valid,total,1))*100), projected: jobs.reduce((s,j)=>s+j.projected,0), conflicts: jobs.reduce((s,j)=>s+j.conflicts,0) }; },[jobs,valid,total]);
  async function refresh(current=jobs) { const next: Status[]=[]; for (const job of current) { if(terminal.has(job.state)){ next.push(job); continue; } const r=await fetch(`/api/admin/inventory/import-bulk-jobs/${encodeURIComponent(job.jobId)}`,{cache:"no-store"}); next.push(r.ok ? await r.json() as Status : job); } setJobs(next); return next; }
  async function submit(items: StockImportItem[], current: Status[]) { let tracked=current; while(!abort.current && tracked.filter(j=>!terminal.has(j.state)).length>=2){ setMessage("Inventory mantiene 2 jobs activos. Esperando capacidad."); await sleep(3000); tracked=await refresh(tracked); } const r=await fetch("/api/admin/inventory/import-bulk-jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operationId:operationId(),maxItems:items.length,items})}); const body=await r.json().catch(()=>({})) as Status & { error?: string }; if(!r.ok) throw new Error(body.error ?? "No se pudo crear job de stock."); const next=[...tracked,body]; setJobs(next); return next; }
  async function handle(file: File | null) { abort.current=false; setError(null); setRowErrors([]); setJobs([]); setTotal(0); setValid(0); setFileName(file?.name??null); if(!file){setPhase("idle");return;} if(!isCsvFile(file)){setPhase("failed");setError("Archivo no válido. Sube un CSV; no se aceptan PDF, Excel ni imágenes.");return;} try{ setPhase("validating"); setMessage("Leyendo CSV de stock..."); const rows=parseCsv(await file.text()); setTotal(rows.length); let chunk: StockImportItem[]=[]; let accepted=0; let tracked: Status[]=[]; const errors: string[]=[]; setPhase("submitting"); for(const {row,rowNumber} of rows){ const converted=rowToItem(row,rowNumber); if(converted.error){ if(errors.length<20) errors.push(converted.error); continue; } if(!converted.item) continue; chunk.push(converted.item); accepted+=1; setValid(accepted); if(chunk.length===chunkSize){ setMessage(`Enviando ${accepted.toLocaleString("es-ES")} filas válidas...`); tracked=await submit(chunk,tracked); chunk=[]; } } setRowErrors(errors); if(!accepted) throw new Error(errors[0] ?? "No hay filas válidas."); if(chunk.length) tracked=await submit(chunk,tracked); setPhase("polling"); setMessage("Jobs de stock creados. Consultando progreso."); while(!abort.current && tracked.some(j=>!terminal.has(j.state))){ await sleep(3000); tracked=await refresh(tracked); } setPhase(tracked.some(j=>j.state==="FAILED")?"failed":"completed"); setMessage(tracked.some(j=>j.state==="FAILED")?"Uno o más jobs fallaron.":"Importación de stock finalizada o entregada a workers."); } catch(e){ setPhase("failed"); setError(e instanceof Error ? e.message : "No se pudo procesar el CSV de stock."); } }
  const busy=["validating","submitting","polling"].includes(phase);
  return <section className="adminCard pricingBulkImportCard"><div className="adminCardHeader"><div><h2>Importar stock por CSV</h2><p>Actualiza stock por variante en jobs bulk de Inventory, con chunks de 10.000 filas y seguimiento de proyección.</p></div><span className={`adminBadge ${phase==="completed"?"adminBadgeOk":phase==="failed"?"adminBadgeError":""}`}>{phase}</span></div>{error?<div className="adminBanner adminBannerError"><p>{error}</p></div>:null}<div className="adminBanner adminBannerInfo"><p>CSV esperado: <code>variantId,warehouseId,onHandQuantity</code>. Opcionales: <code>reservedQuantity</code>, <code>safetyStockQuantity</code>, <code>quarantineQuantity</code>.</p></div><div className="pricingBulkImportDropzone"><label className="adminField pricingBulkImportFileField"><span>CSV de stock</span><input accept=".csv,text/csv" disabled={busy} onChange={(event)=>void handle(event.currentTarget.files?.[0]??null)} type="file" /></label><div className="adminButtonRow">{busy?<button className="adminButton" onClick={()=>{abort.current=true;}} type="button">Detener seguimiento</button>:null}<a className="adminButton" download="stock-bulk-template.csv" href="data:text/csv;charset=utf-8,variantId,warehouseId,onHandQuantity,reservedQuantity,safetyStockQuantity%0Aaaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa,main-warehouse,25,0,2%0A">Descargar plantilla</a></div></div><div className="pricingBulkImportProgress" aria-live="polite"><div className="pricingBulkImportProgressHeader"><strong>{fileName??"Sin archivo"}</strong><span>{message}</span></div><div className="pricingBulkImportProgressTrack" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress.percent}><span style={{width:`${Math.min(100,Math.max(0,progress.percent))}%`}} /></div><div className="pricingBulkImportMetrics"><span>Total: {total.toLocaleString("es-ES")}</span><span>Válidas: {valid.toLocaleString("es-ES")}</span><span>Procesadas: {progress.done.toLocaleString("es-ES")}</span><span>Proyectadas: {progress.projected.toLocaleString("es-ES")}</span><span>Conflictos: {progress.conflicts.toLocaleString("es-ES")}</span><span>Tenant: {context.organizationId || "-"} / {context.shopId || "-"}</span></div></div>{rowErrors.length?<details className="pricingBulkImportErrors"><summary>{rowErrors.length} errores de validación mostrados</summary><ul className="adminPlainList">{rowErrors.map(item=><li key={item}>{item}</li>)}</ul></details>:null}</section>;
}
